---
branches:
  only:
    - master
    - develop
    - /^feature/.*$/
language: node_js
node_js:
  - stable
  - "--lts"
env:
  global:
    - CC_TEST_REPORTER_ID=2d8ee90a637389c06572471731912653fa7b0dcaa8ce73fe470f196d63e0d04b
before_install:
  - npm i -g npm
install: npm ci --no-optional
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
after_script:
  - "[ $TRAVIS_NODE_VERSION = stable ] && c8 report --reporter=lcov --reporter=text && ./cc-test-reporter
    after-build --debug -t lcov --exit-code $TRAVIS_TEST_RESULT || echo 'Coverage skipped'"
notifications:
  slack:
    secure: ZTrPXF+4Ka2nAq5rNFSn8FGUXTk6EYBug5C4OtnEt4ECtzVXIm+51ZisUBagjkrMAOdFHZbTgGcWPAv8TQA8EWIGlfVzdDLXcejwMHhixxoLsBsfTnsN9tacV6e9xvFOWuG6/Y/F89214VCMODh8I8To9LvAbgVdFxyLh2OcfuQ=
cache:
  directories:
    - "$HOME/.npm"
